CREATE TABLE IF NOT EXISTS characters(
    id integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    picture text,
    Name text NOT NULL CHECK (name <> ''),
    age integer NOT NULL,
    weight integer NOT NULL,
    story text NOT NULL
);

CREATE TABLE IF NOT EXISTS tasks(
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    name text NOT NULL CHECK (name <> ''),
    done BOOLEAN,
    projectid INTEGER REFERENCES projects(id)
);


INSERT INTO projects(name, priority, description, deliverydate)
values ('Make a Web App', 1, 'Using Javascript', '2019-05-12');

INSERT INTO projects(name, priority, description, deliverydate)
values ('Make a gaming App', 1, 'Using Phyton', '2019-05-12');

INSERT INTO projects(name, priority, description, deliverydate)
values ('Make an App', 1, 'Using Java', '2019-05-03');

-- INSERT TASKS DATA

INSERT INTO movies(picture, title, creationdate, rating)
values('my picture', 'my title 13 4', '2020-03-21', 1)

INSERT INTO tasks(name, done, porjectID)
values('download Vuejs', false, 1)